// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ADMIN_NET_PROTOCOL_H_
#define FLATBUFFERS_GENERATED_ADMIN_NET_PROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace net {
namespace protocol {

struct show_server_stats;
struct show_server_statsBuilder;

struct show_server_stats FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef show_server_statsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_IS_RUNNING = 4
  };
  bool is_running() const {
    return GetField<uint8_t>(VT_IS_RUNNING, 0) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_IS_RUNNING, 1) &&
           verifier.EndTable();
  }
};

struct show_server_statsBuilder {
  typedef show_server_stats Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_is_running(bool is_running) {
    fbb_.AddElement<uint8_t>(show_server_stats::VT_IS_RUNNING, static_cast<uint8_t>(is_running), 0);
  }
  explicit show_server_statsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<show_server_stats> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<show_server_stats>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<show_server_stats> Createshow_server_stats(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool is_running = false) {
  show_server_statsBuilder builder_(_fbb);
  builder_.add_is_running(is_running);
  return builder_.Finish();
}

}  // namespace protocol
}  // namespace net

#endif  // FLATBUFFERS_GENERATED_ADMIN_NET_PROTOCOL_H_
