// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CLIENT_NET_PROTOCOL_H_
#define FLATBUFFERS_GENERATED_CLIENT_NET_PROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace net {
namespace protocol {

struct transform;
struct transformBuilder;

struct instantiate;
struct instantiateBuilder;

struct chat;
struct chatBuilder;

struct mouse_point;
struct mouse_pointBuilder;

struct attack;
struct attackBuilder;

enum chat_type_id : int8_t {
  chat_type_id_TEXT = 0,
  chat_type_id_IMAGE = 1,
  chat_type_id_SYSTEM = 2,
  chat_type_id_MIN = chat_type_id_TEXT,
  chat_type_id_MAX = chat_type_id_SYSTEM
};

inline const chat_type_id (&EnumValueschat_type_id())[3] {
  static const chat_type_id values[] = {
    chat_type_id_TEXT,
    chat_type_id_IMAGE,
    chat_type_id_SYSTEM
  };
  return values;
}

inline const char * const *EnumNameschat_type_id() {
  static const char * const names[4] = {
    "TEXT",
    "IMAGE",
    "SYSTEM",
    nullptr
  };
  return names;
}

inline const char *EnumNamechat_type_id(chat_type_id e) {
  if (::flatbuffers::IsOutRange(e, chat_type_id_TEXT, chat_type_id_SYSTEM)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNameschat_type_id()[index];
}

struct transform FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef transformBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POSITION_X = 4,
    VT_POSITION_Y = 6,
    VT_POSITION_Z = 8
  };
  float position_x() const {
    return GetField<float>(VT_POSITION_X, 0.0f);
  }
  float position_y() const {
    return GetField<float>(VT_POSITION_Y, 0.0f);
  }
  float position_z() const {
    return GetField<float>(VT_POSITION_Z, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_POSITION_X, 4) &&
           VerifyField<float>(verifier, VT_POSITION_Y, 4) &&
           VerifyField<float>(verifier, VT_POSITION_Z, 4) &&
           verifier.EndTable();
  }
};

struct transformBuilder {
  typedef transform Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_position_x(float position_x) {
    fbb_.AddElement<float>(transform::VT_POSITION_X, position_x, 0.0f);
  }
  void add_position_y(float position_y) {
    fbb_.AddElement<float>(transform::VT_POSITION_Y, position_y, 0.0f);
  }
  void add_position_z(float position_z) {
    fbb_.AddElement<float>(transform::VT_POSITION_Z, position_z, 0.0f);
  }
  explicit transformBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<transform> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<transform>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<transform> Createtransform(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float position_x = 0.0f,
    float position_y = 0.0f,
    float position_z = 0.0f) {
  transformBuilder builder_(_fbb);
  builder_.add_position_z(position_z);
  builder_.add_position_y(position_y);
  builder_.add_position_x(position_x);
  return builder_.Finish();
}

struct instantiate FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef instantiateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJECT_ID = 4,
    VT_PREFAB_ID = 6,
    VT_OBJECT_TRANSFORM = 8
  };
  uint64_t object_id() const {
    return GetField<uint64_t>(VT_OBJECT_ID, 0);
  }
  int32_t prefab_id() const {
    return GetField<int32_t>(VT_PREFAB_ID, 0);
  }
  const net::protocol::transform *object_transform() const {
    return GetPointer<const net::protocol::transform *>(VT_OBJECT_TRANSFORM);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_OBJECT_ID, 8) &&
           VerifyField<int32_t>(verifier, VT_PREFAB_ID, 4) &&
           VerifyOffset(verifier, VT_OBJECT_TRANSFORM) &&
           verifier.VerifyTable(object_transform()) &&
           verifier.EndTable();
  }
};

struct instantiateBuilder {
  typedef instantiate Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_object_id(uint64_t object_id) {
    fbb_.AddElement<uint64_t>(instantiate::VT_OBJECT_ID, object_id, 0);
  }
  void add_prefab_id(int32_t prefab_id) {
    fbb_.AddElement<int32_t>(instantiate::VT_PREFAB_ID, prefab_id, 0);
  }
  void add_object_transform(::flatbuffers::Offset<net::protocol::transform> object_transform) {
    fbb_.AddOffset(instantiate::VT_OBJECT_TRANSFORM, object_transform);
  }
  explicit instantiateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<instantiate> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<instantiate>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<instantiate> Createinstantiate(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t object_id = 0,
    int32_t prefab_id = 0,
    ::flatbuffers::Offset<net::protocol::transform> object_transform = 0) {
  instantiateBuilder builder_(_fbb);
  builder_.add_object_id(object_id);
  builder_.add_object_transform(object_transform);
  builder_.add_prefab_id(prefab_id);
  return builder_.Finish();
}

struct chat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef chatBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE_ID = 4,
    VT_USER_ID = 6,
    VT_CONTENT = 8,
    VT_TIMESTAMP = 10
  };
  net::protocol::chat_type_id type_id() const {
    return static_cast<net::protocol::chat_type_id>(GetField<int8_t>(VT_TYPE_ID, 0));
  }
  uint64_t user_id() const {
    return GetField<uint64_t>(VT_USER_ID, 0);
  }
  const ::flatbuffers::String *content() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CONTENT);
  }
  int64_t timestamp() const {
    return GetField<int64_t>(VT_TIMESTAMP, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_TYPE_ID, 1) &&
           VerifyField<uint64_t>(verifier, VT_USER_ID, 8) &&
           VerifyOffset(verifier, VT_CONTENT) &&
           verifier.VerifyString(content()) &&
           VerifyField<int64_t>(verifier, VT_TIMESTAMP, 8) &&
           verifier.EndTable();
  }
};

struct chatBuilder {
  typedef chat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type_id(net::protocol::chat_type_id type_id) {
    fbb_.AddElement<int8_t>(chat::VT_TYPE_ID, static_cast<int8_t>(type_id), 0);
  }
  void add_user_id(uint64_t user_id) {
    fbb_.AddElement<uint64_t>(chat::VT_USER_ID, user_id, 0);
  }
  void add_content(::flatbuffers::Offset<::flatbuffers::String> content) {
    fbb_.AddOffset(chat::VT_CONTENT, content);
  }
  void add_timestamp(int64_t timestamp) {
    fbb_.AddElement<int64_t>(chat::VT_TIMESTAMP, timestamp, 0);
  }
  explicit chatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<chat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<chat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<chat> Createchat(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    net::protocol::chat_type_id type_id = net::protocol::chat_type_id_TEXT,
    uint64_t user_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> content = 0,
    int64_t timestamp = 0) {
  chatBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_user_id(user_id);
  builder_.add_content(content);
  builder_.add_type_id(type_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<chat> CreatechatDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    net::protocol::chat_type_id type_id = net::protocol::chat_type_id_TEXT,
    uint64_t user_id = 0,
    const char *content = nullptr,
    int64_t timestamp = 0) {
  auto content__ = content ? _fbb.CreateString(content) : 0;
  return net::protocol::Createchat(
      _fbb,
      type_id,
      user_id,
      content__,
      timestamp);
}

struct mouse_point FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef mouse_pointBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POSITION_X = 4,
    VT_POSITION_Y = 6
  };
  float position_x() const {
    return GetField<float>(VT_POSITION_X, 0.0f);
  }
  float position_y() const {
    return GetField<float>(VT_POSITION_Y, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_POSITION_X, 4) &&
           VerifyField<float>(verifier, VT_POSITION_Y, 4) &&
           verifier.EndTable();
  }
};

struct mouse_pointBuilder {
  typedef mouse_point Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_position_x(float position_x) {
    fbb_.AddElement<float>(mouse_point::VT_POSITION_X, position_x, 0.0f);
  }
  void add_position_y(float position_y) {
    fbb_.AddElement<float>(mouse_point::VT_POSITION_Y, position_y, 0.0f);
  }
  explicit mouse_pointBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<mouse_point> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<mouse_point>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<mouse_point> Createmouse_point(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float position_x = 0.0f,
    float position_y = 0.0f) {
  mouse_pointBuilder builder_(_fbb);
  builder_.add_position_y(position_y);
  builder_.add_position_x(position_x);
  return builder_.Finish();
}

struct attack FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef attackBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJECT_ID = 4,
    VT_DAMAGE = 6
  };
  uint64_t object_id() const {
    return GetField<uint64_t>(VT_OBJECT_ID, 0);
  }
  int32_t damage() const {
    return GetField<int32_t>(VT_DAMAGE, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_OBJECT_ID, 8) &&
           VerifyField<int32_t>(verifier, VT_DAMAGE, 4) &&
           verifier.EndTable();
  }
};

struct attackBuilder {
  typedef attack Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_object_id(uint64_t object_id) {
    fbb_.AddElement<uint64_t>(attack::VT_OBJECT_ID, object_id, 0);
  }
  void add_damage(int32_t damage) {
    fbb_.AddElement<int32_t>(attack::VT_DAMAGE, damage, 0);
  }
  explicit attackBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<attack> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<attack>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<attack> Createattack(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t object_id = 0,
    int32_t damage = 0) {
  attackBuilder builder_(_fbb);
  builder_.add_object_id(object_id);
  builder_.add_damage(damage);
  return builder_.Finish();
}

}  // namespace protocol
}  // namespace net

#endif  // FLATBUFFERS_GENERATED_CLIENT_NET_PROTOCOL_H_
