// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PACKET_NET_PROTOCOL_H_
#define FLATBUFFERS_GENERATED_PACKET_NET_PROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "admin_generated.h"
#include "client_generated.h"

namespace net {
namespace protocol {

struct packet_header;

struct packet;
struct packetBuilder;

enum packet_id_type : uint16_t {
  packet_id_type_PACKET_TYPE_NONE = 0,
  packet_id_type_SHOW_SERVER_STATS = 10000,
  packet_id_type_TRANSFORM = 20000,
  packet_id_type_INSTANTIATE = 20001,
  packet_id_type_CHAT = 20002,
  packet_id_type_MOUSE_POINT = 20003,
  packet_id_type_ATTACK = 20004,
  packet_id_type_MIN = packet_id_type_PACKET_TYPE_NONE,
  packet_id_type_MAX = packet_id_type_ATTACK
};

inline const packet_id_type (&EnumValuespacket_id_type())[7] {
  static const packet_id_type values[] = {
    packet_id_type_PACKET_TYPE_NONE,
    packet_id_type_SHOW_SERVER_STATS,
    packet_id_type_TRANSFORM,
    packet_id_type_INSTANTIATE,
    packet_id_type_CHAT,
    packet_id_type_MOUSE_POINT,
    packet_id_type_ATTACK
  };
  return values;
}

inline const char *EnumNamepacket_id_type(packet_id_type e) {
  switch (e) {
    case packet_id_type_PACKET_TYPE_NONE: return "PACKET_TYPE_NONE";
    case packet_id_type_SHOW_SERVER_STATS: return "SHOW_SERVER_STATS";
    case packet_id_type_TRANSFORM: return "TRANSFORM";
    case packet_id_type_INSTANTIATE: return "INSTANTIATE";
    case packet_id_type_CHAT: return "CHAT";
    case packet_id_type_MOUSE_POINT: return "MOUSE_POINT";
    case packet_id_type_ATTACK: return "ATTACK";
    default: return "";
  }
}

enum packet_flow_type : int8_t {
  packet_flow_type_S2C = 0,
  packet_flow_type_C2S = 1,
  packet_flow_type_MIN = packet_flow_type_S2C,
  packet_flow_type_MAX = packet_flow_type_C2S
};

inline const packet_flow_type (&EnumValuespacket_flow_type())[2] {
  static const packet_flow_type values[] = {
    packet_flow_type_S2C,
    packet_flow_type_C2S
  };
  return values;
}

inline const char * const *EnumNamespacket_flow_type() {
  static const char * const names[3] = {
    "S2C",
    "C2S",
    nullptr
  };
  return names;
}

inline const char *EnumNamepacket_flow_type(packet_flow_type e) {
  if (::flatbuffers::IsOutRange(e, packet_flow_type_S2C, packet_flow_type_C2S)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamespacket_flow_type()[index];
}

enum packet_payload : uint8_t {
  packet_payload_NONE = 0,
  packet_payload_show_server_stats = 1,
  packet_payload_transform = 2,
  packet_payload_instantiate = 3,
  packet_payload_chat = 4,
  packet_payload_mouse_point = 5,
  packet_payload_attack = 6,
  packet_payload_MIN = packet_payload_NONE,
  packet_payload_MAX = packet_payload_attack
};

inline const packet_payload (&EnumValuespacket_payload())[7] {
  static const packet_payload values[] = {
    packet_payload_NONE,
    packet_payload_show_server_stats,
    packet_payload_transform,
    packet_payload_instantiate,
    packet_payload_chat,
    packet_payload_mouse_point,
    packet_payload_attack
  };
  return values;
}

inline const char * const *EnumNamespacket_payload() {
  static const char * const names[8] = {
    "NONE",
    "show_server_stats",
    "transform",
    "instantiate",
    "chat",
    "mouse_point",
    "attack",
    nullptr
  };
  return names;
}

inline const char *EnumNamepacket_payload(packet_payload e) {
  if (::flatbuffers::IsOutRange(e, packet_payload_NONE, packet_payload_attack)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamespacket_payload()[index];
}

template<typename T> struct packet_payloadTraits {
  static const packet_payload enum_value = packet_payload_NONE;
};

template<> struct packet_payloadTraits<net::protocol::show_server_stats> {
  static const packet_payload enum_value = packet_payload_show_server_stats;
};

template<> struct packet_payloadTraits<net::protocol::transform> {
  static const packet_payload enum_value = packet_payload_transform;
};

template<> struct packet_payloadTraits<net::protocol::instantiate> {
  static const packet_payload enum_value = packet_payload_instantiate;
};

template<> struct packet_payloadTraits<net::protocol::chat> {
  static const packet_payload enum_value = packet_payload_chat;
};

template<> struct packet_payloadTraits<net::protocol::mouse_point> {
  static const packet_payload enum_value = packet_payload_mouse_point;
};

template<> struct packet_payloadTraits<net::protocol::attack> {
  static const packet_payload enum_value = packet_payload_attack;
};

template <bool B = false>
bool Verifypacket_payload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, packet_payload type);
template <bool B = false>
bool Verifypacket_payloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) packet_header FLATBUFFERS_FINAL_CLASS {
 private:
  int8_t flow_type_;
  int8_t padding0__;
  uint16_t type_id_;
  uint32_t connection_id_;
  uint32_t timestamp_;
  uint16_t sequence_;
  uint16_t payload_size_;
  uint16_t checksum_;
  int16_t padding1__;

 public:
  packet_header()
      : flow_type_(0),
        padding0__(0),
        type_id_(0),
        connection_id_(0),
        timestamp_(0),
        sequence_(0),
        payload_size_(0),
        checksum_(0),
        padding1__(0) {
    (void)padding0__;
    (void)padding1__;
  }
  packet_header(net::protocol::packet_flow_type _flow_type, net::protocol::packet_id_type _type_id, uint32_t _connection_id, uint32_t _timestamp, uint16_t _sequence, uint16_t _payload_size, uint16_t _checksum)
      : flow_type_(::flatbuffers::EndianScalar(static_cast<int8_t>(_flow_type))),
        padding0__(0),
        type_id_(::flatbuffers::EndianScalar(static_cast<uint16_t>(_type_id))),
        connection_id_(::flatbuffers::EndianScalar(_connection_id)),
        timestamp_(::flatbuffers::EndianScalar(_timestamp)),
        sequence_(::flatbuffers::EndianScalar(_sequence)),
        payload_size_(::flatbuffers::EndianScalar(_payload_size)),
        checksum_(::flatbuffers::EndianScalar(_checksum)),
        padding1__(0) {
    (void)padding0__;
    (void)padding1__;
  }
  net::protocol::packet_flow_type flow_type() const {
    return static_cast<net::protocol::packet_flow_type>(::flatbuffers::EndianScalar(flow_type_));
  }
  net::protocol::packet_id_type type_id() const {
    return static_cast<net::protocol::packet_id_type>(::flatbuffers::EndianScalar(type_id_));
  }
  uint32_t connection_id() const {
    return ::flatbuffers::EndianScalar(connection_id_);
  }
  uint32_t timestamp() const {
    return ::flatbuffers::EndianScalar(timestamp_);
  }
  uint16_t sequence() const {
    return ::flatbuffers::EndianScalar(sequence_);
  }
  uint16_t payload_size() const {
    return ::flatbuffers::EndianScalar(payload_size_);
  }
  uint16_t checksum() const {
    return ::flatbuffers::EndianScalar(checksum_);
  }
};
FLATBUFFERS_STRUCT_END(packet_header, 20);

struct packet FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef packetBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HEADER = 4,
    VT_PAYLOAD_TYPE = 6,
    VT_PAYLOAD = 8
  };
  const net::protocol::packet_header *header() const {
    return GetStruct<const net::protocol::packet_header *>(VT_HEADER);
  }
  net::protocol::packet_payload payload_type() const {
    return static_cast<net::protocol::packet_payload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const net::protocol::show_server_stats *payload_as_show_server_stats() const {
    return payload_type() == net::protocol::packet_payload_show_server_stats ? static_cast<const net::protocol::show_server_stats *>(payload()) : nullptr;
  }
  const net::protocol::transform *payload_as_transform() const {
    return payload_type() == net::protocol::packet_payload_transform ? static_cast<const net::protocol::transform *>(payload()) : nullptr;
  }
  const net::protocol::instantiate *payload_as_instantiate() const {
    return payload_type() == net::protocol::packet_payload_instantiate ? static_cast<const net::protocol::instantiate *>(payload()) : nullptr;
  }
  const net::protocol::chat *payload_as_chat() const {
    return payload_type() == net::protocol::packet_payload_chat ? static_cast<const net::protocol::chat *>(payload()) : nullptr;
  }
  const net::protocol::mouse_point *payload_as_mouse_point() const {
    return payload_type() == net::protocol::packet_payload_mouse_point ? static_cast<const net::protocol::mouse_point *>(payload()) : nullptr;
  }
  const net::protocol::attack *payload_as_attack() const {
    return payload_type() == net::protocol::packet_payload_attack ? static_cast<const net::protocol::attack *>(payload()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<net::protocol::packet_header>(verifier, VT_HEADER, 4) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           Verifypacket_payload(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const net::protocol::show_server_stats *packet::payload_as<net::protocol::show_server_stats>() const {
  return payload_as_show_server_stats();
}

template<> inline const net::protocol::transform *packet::payload_as<net::protocol::transform>() const {
  return payload_as_transform();
}

template<> inline const net::protocol::instantiate *packet::payload_as<net::protocol::instantiate>() const {
  return payload_as_instantiate();
}

template<> inline const net::protocol::chat *packet::payload_as<net::protocol::chat>() const {
  return payload_as_chat();
}

template<> inline const net::protocol::mouse_point *packet::payload_as<net::protocol::mouse_point>() const {
  return payload_as_mouse_point();
}

template<> inline const net::protocol::attack *packet::payload_as<net::protocol::attack>() const {
  return payload_as_attack();
}

struct packetBuilder {
  typedef packet Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_header(const net::protocol::packet_header *header) {
    fbb_.AddStruct(packet::VT_HEADER, header);
  }
  void add_payload_type(net::protocol::packet_payload payload_type) {
    fbb_.AddElement<uint8_t>(packet::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(packet::VT_PAYLOAD, payload);
  }
  explicit packetBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<packet> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<packet>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<packet> Createpacket(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const net::protocol::packet_header *header = nullptr,
    net::protocol::packet_payload payload_type = net::protocol::packet_payload_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  packetBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_header(header);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

template <bool B>
inline bool Verifypacket_payload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, packet_payload type) {
  switch (type) {
    case packet_payload_NONE: {
      return true;
    }
    case packet_payload_show_server_stats: {
      auto ptr = reinterpret_cast<const net::protocol::show_server_stats *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case packet_payload_transform: {
      auto ptr = reinterpret_cast<const net::protocol::transform *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case packet_payload_instantiate: {
      auto ptr = reinterpret_cast<const net::protocol::instantiate *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case packet_payload_chat: {
      auto ptr = reinterpret_cast<const net::protocol::chat *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case packet_payload_mouse_point: {
      auto ptr = reinterpret_cast<const net::protocol::mouse_point *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case packet_payload_attack: {
      auto ptr = reinterpret_cast<const net::protocol::attack *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool Verifypacket_payloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!Verifypacket_payload(
        verifier,  values->Get(i), types->GetEnum<packet_payload>(i))) {
      return false;
    }
  }
  return true;
}

inline const net::protocol::packet *Getpacket(const void *buf) {
  return ::flatbuffers::GetRoot<net::protocol::packet>(buf);
}

inline const net::protocol::packet *GetSizePrefixedpacket(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<net::protocol::packet>(buf);
}

template <bool B = false>
inline bool VerifypacketBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<net::protocol::packet>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedpacketBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<net::protocol::packet>(nullptr);
}

inline void FinishpacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<net::protocol::packet> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedpacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<net::protocol::packet> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace protocol
}  // namespace net

#endif  // FLATBUFFERS_GENERATED_PACKET_NET_PROTOCOL_H_
